"""benchlab importer — convert public agent-benchmark tasks into JayNet eval cases.

Supported sources:

  terminal-bench   laude-institute/terminal-bench (Apache-2.0), cloned by
                   bench.fetch into the data-dir cache; tasks live under
                   original-tasks/<name>/ (task.yaml + Dockerfile + tests/).
                   Two import modes: "lite" (curated container-free subset,
                   fixtures + embedded pytest checker) and "full" (any task —
                   the Dockerfile is built into a podman image at import and
                   the case runs inside that container; grading pytest is
                   staged host-side and podman-cp'd in at grade time).
  gaia             gaia-benchmark/GAIA (gated HF dataset, CC-BY-4.0 — the
                   admin's own HF_TOKEN is required), Level-1 validation rows
                   via the HF datasets-server HTTP API + file resolve URLs.

Every produced case is validated with runtime.eval_cases.validate_case_dict
before writing and parsed back afterwards; only tb-*/gaia-* files the importer
itself generated are ever (over)written.
"""

from __future__ import annotations

import base64
import hashlib
import json
import logging
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import zlib
from pathlib import Path, PurePosixPath

import yaml

from runtime.eval_cases import parse_case, validate_case_dict

log = logging.getLogger(__name__)


class SkipTask(Exception):
    """A benchmark task that cannot become a sound container-free eval case."""


# ---- terminal-bench -----------------------------------------------------------

TB_REPO_URL = "https://github.com/laude-institute/terminal-bench.git"
TB_TASKS_SUBDIR = "original-tasks"

# Curated container-free subset — the default bench.import task set.
# Built by inspecting the cloned catalog (original-tasks/, 241 tasks @ 2026-08):
# EXCLUDED tasks whose Dockerfile runs apt/pip/uv/curl/wget/git-clone/npm/conda
# installs, starts services, needs network/GPU, or whose tests import non-stdlib
# packages or call non-stdlib binaries; also excluded: fixtures generated by
# build-time RUN scripts >64KB compressed (jsonl-aggregator 17MB,
# weighted-max-sat-solver 7.8MB, gcode-to-text 1.6MB), date-fragile fixtures
# (log-summary-date-ranges bakes in 2025-08-12), timing-flaky speedup asserts
# (parallelize-compute-squares), non-stdlib solving stacks (classifier-debug
# needs torch, dna-* need primer3's oligotm binary), interactive/server games
# (blind-maze-*), and binary-bundle fixtures (merge-diff-arc-agi-task).
# INCLUDED: tasks solvable with python3 stdlib + basic shell in an empty dir,
# with pytest tests that grade files under /app (rewritten to the eval sandbox).
CURATED_TB_TASKS = (
    "hello-world",               # write hello.txt — trivial smoke case
    "analyze-access-logs",       # parse shipped access_log → report.txt
    "regex-log",                 # write a date-in-IP-lines regex to regex.txt
    "countdown-game",            # arithmetic expression puzzle → output.txt
    "fix-permissions",           # chmod +x a shipped script so it runs
    "recover-obfuscated-files",  # base64-decode filenames+contents → recovered/
    "assign-seats",              # decode pkl/b64/txt clues, solve seating CSP
    "mahjong-winninghand",       # classify 8 shipped mahjong hands → result.txt
    "huarong-dao-solver",        # solve sliding puzzle, write solution.json
    "recover-accuracy-log",      # split interleaved gen/judge logs per run
)

# Extra seed_code per task, mirroring Dockerfile RUN lines the grading tests
# actually depend on (file modes / pre-created dirs the agent is told about).
TB_SEED_EXTRA = {
    "fix-permissions": ("import os; os.chmod('process_data.sh', 0o644)",),
    "recover-accuracy-log": ("import os; os.makedirs('recovered_logs', exist_ok=True)",),
}

TB_JUDGE_RUBRIC = ("Deterministic checker is authoritative: pass iff checks "
                   "passed and the agent genuinely attempted the task "
                   "(no refusal, no error-out).")

_ID_OK = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_-]*$")
_INSTALL_RE = re.compile(
    r"(?i)^RUN\s+(apt|apt-get|apk|pip|pip3|uv|curl|wget|git|npm|npx|conda|"
    r"mamba|dpkg|snap|service|systemctl|yum|dnf|brew|cargo|go)\b")


def sanitize_task_id(prefix: str, name: str) -> str:
    """`tb-`/`gaia-` + a case-id-safe form of the upstream task name."""
    clean = re.sub(r"[^a-zA-Z0-9_-]+", "-", str(name)).strip("-_").lower()
    clean = re.sub(r"-{2,}", "-", clean) or "task"
    if not clean[0].isalnum():
        clean = "x" + clean
    cid = f"{prefix}-{clean}"
    if not _ID_OK.match(cid):            # paranoia: prefix guarantees this
        raise SkipTask(f"cannot derive a valid case id from '{name}'")
    return cid


def scan_tb_catalog(root: Path) -> dict[str, list[str]]:
    """{task_name: [exclusion reasons]} over a cloned catalog; an empty list
    marks a container-free candidate. Heuristic, for bench.fetch reporting —
    the curated tuple above is the audited default import set."""
    root = Path(root)
    out: dict[str, list[str]] = {}
    if not root.is_dir():
        return out
    for d in sorted(p for p in root.iterdir() if p.is_dir()):
        if not (d / "task.yaml").is_file():
            continue
        reasons: list[str] = []
        df = d / "Dockerfile"
        if df.is_file():
            for line in df.read_text(errors="replace").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and _INSTALL_RE.match(line):
                    reasons.append(f"container setup: {line[:80]}")
        pytests = sorted((d / "tests").rglob("*.py")) if (d / "tests").is_dir() else []
        if not pytests:
            reasons.append("no pytest tests")
        else:
            deps: set[str] = set()
            for tf in pytests:
                for m in re.finditer(r"^\s*(?:from|import)\s+([A-Za-z0-9_]+)",
                                     tf.read_text(errors="replace"), re.M):
                    deps.add(m.group(1))
            nonstd = sorted(x for x in deps
                            if x not in sys.stdlib_module_names and x != "pytest")
            if nonstd:
                reasons.append("tests need non-stdlib: " + ", ".join(nonstd))
        out[d.name] = reasons
    return out


# ---- fixture extraction (Dockerfile COPY → project files) ----------------------

_COPY_RE = re.compile(r"(?i)^COPY\s+(.+)$")
_TEXT_LIMIT = 64 * 1024          # larger text fixtures go in as compressed blobs
_BLOB_BUDGET = 512 * 1024        # total compressed blob bytes per case


def _collect_fixtures(task_dir: Path, dockerfile: str) -> dict[str, bytes]:
    """Interpret simple Docker COPY lines into {work_root_relpath: bytes}.

    Handles: single files, `dir/` (contents land IN the dest, Docker-style) and
    globs (`protected/*.json`). Destinations outside /app (e.g. /protected) are
    skipped — the eval sandbox only mirrors the agent's work dir. Grading
    files (tests/, solution/run-tests scripts) are never fixtures."""
    fixtures: dict[str, bytes] = {}
    for raw in dockerfile.splitlines():
        m = _COPY_RE.match(raw.strip())
        if not m:
            continue
        parts = [p for p in m.group(1).split() if not p.startswith("--")]
        if len(parts) < 2:
            continue
        srcs, dest = parts[:-1], parts[-1]
        if dest.startswith("/app"):
            dest_rel = dest[4:].lstrip("/")
        elif not dest.startswith("/"):
            dest_rel = dest                     # WORKDIR is /app in TB images
        else:
            continue                            # /protected etc. — not mirrored
        dest_rel = dest_rel.rstrip("/")
        dest_is_dir = dest.endswith("/") or dest_rel in ("", ".")
        for src in srcs:
            src = src.rstrip("/")
            hits = sorted(task_dir.glob(src)) if any(c in src for c in "*?[") \
                else [task_dir / src]
            for p in hits:
                if p.is_dir():
                    base = dest_rel if dest_is_dir else str(
                        PurePosixPath(dest_rel) / p.name)
                    for f in sorted(p.rglob("*")):
                        if f.is_file():
                            rel = PurePosixPath(base) / f.relative_to(p)
                            fixtures[rel.as_posix()] = f.read_bytes()
                elif p.is_file():
                    rel = (PurePosixPath(dest_rel) / p.name).as_posix() \
                        if dest_is_dir else dest_rel
                    fixtures[rel] = p.read_bytes()
    return {r: b for r, b in fixtures.items()
            if not r.startswith(("tests/",)) and r not in (
                "task.yaml", "Dockerfile", "docker-compose.yaml",
                "solution.sh", "solution.yaml", "run-tests.sh")}


def _fixtures_to_project(fixtures: dict[str, bytes],
                         seed_extra: tuple[str, ...] = ()) -> dict:
    """Split fixtures into project.files (UTF-8 text ≤64KB, shown in the file
    tree) and a seed_code snippet that regenerates binary/large ones from
    compressed base64 blobs (keeps the YAML readable)."""
    files: dict[str, str] = {}
    seed: list[str] = []
    budget = _BLOB_BUDGET
    blobs: list[tuple[str, str]] = []
    for rel, data in sorted(fixtures.items()):
        text = None
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            pass
        if text is not None and len(data) <= _TEXT_LIMIT:
            files[rel] = text
            continue
        blob = base64.b64encode(zlib.compress(data, 9)).decode()
        budget -= len(blob)
        if budget < 0:
            raise SkipTask(f"fixtures too large to embed ({rel})")
        blobs.append((rel, blob))
    if blobs:
        seed.append("import base64, os, zlib")
        for rel, blob in blobs:
            seed.append(f"os.makedirs(os.path.dirname({rel!r}) or '.', exist_ok=True)")
            seed.append(f"open({rel!r}, 'wb').write"
                        f"(zlib.decompress(base64.b64decode({blob!r})))")
    seed.extend(seed_extra)
    project: dict = {}
    if files:
        project["files"] = files
    if seed:
        project["seed_code"] = "\n".join(seed)
    return project


# ---- test-code embedding (the deterministic checker) ----------------------------

_APP_PATH_RE = re.compile(r"([fF]?)([\"'])/app(?=[/\"'])")
_TEST_HEADER = 'import os as _bl_os\n_WORKDIR = _bl_os.environ["WORKDIR"]\n'


def _rewrite_test_source(src: str) -> str:
    """TB tests hardcode container paths (/app/...). Rewrite quoted '/app'
    literals to the eval work root (passed as the WORKDIR env var) and define
    _WORKDIR at the top. f-strings get a {_WORKDIR} interpolation instead."""

    def _rep(m: re.Match) -> str:
        prefix, quote = m.group(1), m.group(2)
        if prefix:                                   # f-string: interpolate
            return f"{prefix}{quote}{{_WORKDIR}}"
        return f"_WORKDIR + {quote}"

    out = _APP_PATH_RE.sub(_rep, src)
    if out == src:
        return src
    lines = out.splitlines(keepends=True)
    at = 0
    # a __future__ import must stay first — insert the header after it
    for i, ln in enumerate(lines[:5]):
        if ln.startswith("from __future__"):
            at = i + 1
    lines.insert(at, _TEST_HEADER)
    return "".join(lines)


_CHECKER_TEMPLATE = '''\
import os, pathlib, shutil, subprocess, sys, tempfile

WORKDIR = os.environ.get("EVAL_WORK_ROOT") or os.getcwd()
TESTS = {tests_repr}
VENV = pathlib.Path({venv_repr})

def _pytest_python():
    """A python that HAS pytest. The runtime venv legitimately lacks it
    (grading-only dep — it lives in requirements-test.txt), so: use the
    runtime python when pytest is importable there (dev boxes), else a
    cached checker venv under the benchlab data dir. A venv whose pytest
    install previously failed is REPAIRED here, not trusted — only a
    successful import returns it. Network needed only on the first
    successful bootstrap."""
    def _has(py):
        return subprocess.run([py, "-c", "import pytest"], check=False,
                              stdout=subprocess.DEVNULL,
                              stderr=subprocess.DEVNULL).returncode == 0
    if _has(sys.executable):
        return sys.executable
    cand = str(VENV / ("Scripts/python.exe" if os.name == "nt" else "bin/python"))
    if not pathlib.Path(cand).is_file():
        VENV.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run([sys.executable, "-m", "venv", str(VENV)], check=True)
    if not _has(cand):
        # uv is JayNet's env manager: it needs no pip inside the target
        # venv and can install straight from its local cache. Fall back to
        # the venv's own pip when uv is absent.
        uv = shutil.which("uv")
        if uv:
            subprocess.run([uv, "pip", "install", "--python", cand, "-q",
                            "pytest"], check=True)
        else:
            subprocess.run([cand, "-m", "pip", "install", "-q", "pytest"],
                           check=True)
    return cand

test_dir = tempfile.mkdtemp(prefix="benchlab-tests-")
for rel, src in TESTS.items():
    p = pathlib.Path(test_dir, rel)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(src, encoding="utf-8")
env = dict(os.environ)
env["WORKDIR"] = WORKDIR
env["TEST_DIR"] = test_dir
try:
    py = _pytest_python()
except subprocess.CalledProcessError as e:
    print("checker setup failed: no pytest in the runtime venv and the "
          "checker-venv bootstrap failed (needs network once). Manual fix: "
          "uv pip install --python", VENV / "bin" / "python", "pytest —", e)
    sys.exit(1)
try:
    proc = subprocess.run([py, "-m", "pytest", test_dir, "-q"],
                          cwd=WORKDIR, env=env,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          timeout=100)
except subprocess.TimeoutExpired:
    print("grading pytest timed out")
    sys.exit(1)
if proc.returncode != 0:
    print(proc.stdout.decode("utf-8", errors="replace")[-3000:])
sys.exit(proc.returncode)
'''


def build_checker(test_files: dict[str, str], venv: Path | None = None) -> str:
    """The expect.checker script: materialize the task's tests in a temp dir
    (NOT the work root — the agent must never see grading code), then run
    pytest with cwd = the work root and WORKDIR/TEST_DIR in the env. pytest
    is a grading-only dependency: the script runs it with the runtime python
    when available there, else bootstraps a cached checker venv (`venv`,
    default <data>/benchlab/checker-venv) on first use."""
    if venv is None:
        from runtime import paths
        venv = paths.DATA / "benchlab" / "checker-venv"
    return _CHECKER_TEMPLATE.format(tests_repr=repr(test_files),
                                    venv_repr=repr(str(venv)))


_INSTRUCTION_APP_RE = re.compile(r"/app(?=[/\s\"').,;:]|$)")


def _rewrite_instruction(instruction: str) -> str:
    """The container's /app is the eval sandbox's work root."""
    out = _INSTRUCTION_APP_RE.sub(".", instruction.strip())
    return out + "\n\nWork in the current project directory."


def tb_task_to_case(task_dir: Path,
                    seed_extra: tuple[str, ...] = ()) -> dict:
    """Convert one cloned terminal-bench task dir into an eval case dict.
    Raises SkipTask (with the reason) for anything not sound container-free."""
    task_dir = Path(task_dir)
    name = task_dir.name
    if not task_dir.is_dir():
        raise SkipTask(f"no such task directory: {name}")
    try:
        meta = yaml.safe_load((task_dir / "task.yaml").read_text(
            encoding="utf-8", errors="replace")) or {}
    except yaml.YAMLError as e:
        raise SkipTask(f"bad task.yaml: {e}") from e
    instruction = str(meta.get("instruction") or "").strip()
    if not instruction:
        raise SkipTask("task.yaml has no instruction")
    df_path = task_dir / "Dockerfile"
    dockerfile = df_path.read_text(errors="replace") if df_path.is_file() else ""
    fixtures = _collect_fixtures(task_dir, dockerfile)
    tests_dir = task_dir / "tests"
    test_files: dict[str, str] = {}
    if tests_dir.is_dir():
        for f in sorted(tests_dir.rglob("*")):
            if not f.is_file():
                continue
            rel = f.relative_to(tests_dir).as_posix()
            try:
                src = f.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                raise SkipTask(f"binary test file {rel}") from None
            test_files[rel] = _rewrite_test_source(src) \
                if f.suffix == ".py" else src
    if not any(PurePosixPath(r).name.startswith("test") and r.endswith(".py")
               for r in test_files):
        raise SkipTask("no pytest tests to embed")
    case = {
        "id": sanitize_task_id("tb", name),
        "name": f"Terminal-Bench: {name}",
        "tags": ["bench", "tb"],
        "driver": "scripted",
        "turns": [{"user": _rewrite_instruction(instruction)}],
        "expect": {"checker": build_checker(test_files)},
        "judge_rubric": TB_JUDGE_RUBRIC,
    }
    project = _fixtures_to_project(fixtures, seed_extra)
    if project:
        case["project"] = project
    return case


# ---- terminal-bench FULL mode (podman containers) ------------------------------
#
# Lite mode re-creates the task container-free; full mode runs the case inside
# the task's OWN image, built once at import — much closer to the official
# Terminal-Bench protocol. The generated case carries `container: {image,
# workdir: /app}`; the eval runner starts the container over the case sandbox
# and routes code.run/code.execute into it. Grading: the staged tests are podman-cp'd
# into the still-running container and pytest runs there (EVAL_CONTAINER_ID).

_PODMAN_BUILD_TIMEOUT_S = 3600     # base pulls + apt/pip installs can be slow


def _podman(*args: str, timeout: int = 120) -> tuple[int, bytes]:
    """One podman call: (exit_code, combined_output); never raises."""
    try:
        proc = subprocess.run(["podman", *args], stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, timeout=timeout)
        return proc.returncode, proc.stdout or b""
    except (OSError, subprocess.TimeoutExpired) as e:
        return 127, str(e).encode()


def tb_image_tag(task_dir: Path) -> str:
    """benchlab-tb-<name>-<hash>: the hash covers the Dockerfile content plus
    the task dir's file list, so a rebuilt/changed task gets a new tag while
    unchanged ones reuse the cached image. Raises SkipTask for non-tasks."""
    task_dir = Path(task_dir)
    if not task_dir.is_dir():
        raise SkipTask(f"no such task directory: {task_dir.name}")
    df = task_dir / "Dockerfile"
    if not df.is_file():
        raise SkipTask("no Dockerfile — full mode builds the task's image")
    h = hashlib.sha256()
    h.update(df.read_bytes())
    for f in sorted(task_dir.rglob("*")):
        if f.is_file():
            h.update(f.relative_to(task_dir).as_posix().encode())
    name = re.sub(r"[^a-z0-9]+", "-", task_dir.name.lower()).strip("-") or "task"
    return f"benchlab-tb-{name}-{h.hexdigest()[:12]}"


def build_tb_image(task_dir: Path, tag: str) -> str:
    """Build the task's base image once (skip when already local → "cached",
    else "built"). Test tooling (pytest + the task's test deps) goes on top as
    a separate thin layer (build_test_layer) so adding/changing deps never
    rebuilds the expensive base. Builds need network — base-image pulls and
    the Dockerfile's own installs."""
    rc, _ = _podman("image", "exists", tag)
    if rc == 0:
        return "cached"
    rc, out = _podman("build", "-t", tag, str(task_dir),
                      timeout=_PODMAN_BUILD_TIMEOUT_S)
    if rc != 0:
        tail = out.decode("utf-8", "replace")[-400:].strip()
        raise SkipTask(f"image build failed: {tail or 'podman build error'}")
    return "built"


# ---- test layer (pytest + test deps over the base image) ---------------------
#
# Official Terminal-Bench grades via run-tests.sh, which installs pytest AND
# the tests' own dependencies before running — the container checker executes
# it at grade time when staged (see stage_tb_tests). This layer is the
# FALLBACK for tasks without run-tests.sh and the pytest guarantee overall:
# without it, whole task families grade "import cv2/pandas/psutil failed" no
# matter what the agent produced. Deps are scanned from the test sources'
# imports; the layer tag hashes them, so a deps change rebuilds only this
# seconds-cheap layer, never the base image.

# Bump when the layer recipe itself changes (invalidates cached layer tags).
LAYER_VERSION = "3"

# import name → pip package where they differ (identity lowercase otherwise)
_PIP_MAP = {
    "cv2": "opencv-python-headless",
    "PIL": "pillow",
    "sklearn": "scikit-learn",
    "yaml": "pyyaml",
    "bs4": "beautifulsoup4",
    "imagehash": "ImageHash",
    "dateutil": "python-dateutil",
    "Crypto": "pycryptodome",
    "jwt": "pyjwt",
}
_IMPORT_RE = re.compile(r"^\s*(?:from|import)\s+([A-Za-z0-9_]+)", re.M)
# test-framework / runner modules that never need installing
_DEP_SKIP = {"pytest", "unittest", "tests", "test", "conftest",
             "utils", "util", "common", "helpers", "helper", "run_tests"}


def test_deps(test_files: dict[str, str]) -> list[str]:
    """Sorted pip packages the given test sources import beyond the stdlib.
    Best-effort (import name ≈ package name unless _PIP_MAP says otherwise).

    Modules that exist as local files IN the tests dir (task helpers like
    fit_model.py) are skipped — they ship with the tests, and a pip attempt
    on them used to fail the whole layer build. Anything else unresolvable
    (e.g. the agent's OWN solution module, which tests legitimately import)
    is tolerated per-package at layer build time, not scanned out here."""
    local: set[str] = set()
    for rel in test_files:
        p = PurePosixPath(rel)
        if p.suffix == ".py":
            local.add(p.stem)
        if len(p.parts) > 1:
            local.add(p.parts[0])
    deps: set[str] = set()
    for rel, src in test_files.items():
        if not rel.endswith(".py"):
            continue
        for mod in _IMPORT_RE.findall(src):
            if (mod in _DEP_SKIP or mod in local
                    or mod in sys.stdlib_module_names):
                continue
            deps.add(_PIP_MAP.get(mod, mod.lower()))
    return sorted(deps)


def test_layer_tag(base_tag: str, deps: list[str]) -> str:
    """<base>-t<hash>: hash covers the recipe version + deps, so unchanged
    tasks reuse the cached layer and any recipe/deps change rebuilds only
    this thin layer."""
    h = hashlib.sha256()
    h.update(LAYER_VERSION.encode())
    h.update(base_tag.encode())
    for d in deps:
        h.update(d.encode())
    return f"{base_tag}-t{h.hexdigest()[:12]}"


def build_test_layer(base_tag: str, deps: list[str]) -> str:
    """FROM <base> + pip install pytest <deps> → returns the layer tag
    ("cached" images skip straight to the tag). TB images ship no test
    runner, and grading pytest must run INSIDE the container (runtime has no
    guaranteed network).

    pytest itself is STRICT (no `|| true`: an image without pytest would
    only fail at GRADE time — fail the build here as a clean import-time
    skip, audit D5). The scanned EXTRA deps are per-package TOLERANT: the
    scanner can't tell a pypi package from the agent's own solution module
    (tests legitimately `import attack`), and one unresolvable name must not
    keep the whole task unimportable — a genuinely missing dep still fails
    loudly at grade time with ModuleNotFoundError."""
    tag = test_layer_tag(base_tag, deps)
    rc, _ = _podman("image", "exists", tag)
    if rc == 0:
        return tag
    ctx = tempfile.mkdtemp(prefix="benchlab-test-layer-")
    try:
        lines = [f"FROM {base_tag}",
                 "RUN python3 -m pip install --quiet pytest 2>/dev/null "
                 "|| pip3 install --quiet pytest 2>/dev/null "
                 "|| python3 -m pip install --quiet --break-system-packages "
                 "pytest"]
        for dep in deps:
            lines.append(
                f"RUN python3 -m pip install --quiet {dep} 2>/dev/null "
                f"|| pip3 install --quiet {dep} 2>/dev/null "
                f"|| python3 -m pip install --quiet --break-system-packages "
                f"{dep} "
                f"|| echo 'benchlab: optional test dep {dep} did not "
                f"install'")
        (Path(ctx) / "Containerfile").write_text("\n".join(lines) + "\n",
                                                 encoding="utf-8")
        rc, out = _podman("build", "-t", tag, "-f",
                          str(Path(ctx) / "Containerfile"), ctx,
                          timeout=_PODMAN_BUILD_TIMEOUT_S)
    finally:
        shutil.rmtree(ctx, ignore_errors=True)
    if rc != 0:
        tail = out.decode("utf-8", "replace")[-400:].strip()
        raise SkipTask(f"test layer build failed (deps: "
                       f"{', '.join(deps) or 'none'}): {tail or 'error'}")
    return tag


def stage_tb_tests(task_dir: Path, stage_root: Path) -> Path:
    """Copy the task's tests/ VERBATIM to <stage_root>/<task-name>/ — host-
    side, outside the agent's reach; the container checker podman-cp's them
    into the container at grade time. Verbatim (no /app rewriting): they run
    INSIDE the container, where /app really is the task workdir. The task's
    run-tests.sh (the OFFICIAL grading entry point: installs the test
    toolchain, stages helper dirs, then pytest) rides along when present —
    skipping it grades wrong (feal needs its gcc install, fix-pandas needs
    its `mv $TEST_DIR/src` pre-step). Returns the staged dir."""
    task_dir = Path(task_dir)
    tests = task_dir / "tests"
    if not tests.is_dir():
        raise SkipTask("no tests/ directory to grade with")
    pytests = [f for f in tests.rglob("*.py") if f.name.startswith("test")]
    if not pytests:
        raise SkipTask("no pytest tests to grade with")
    dest = Path(stage_root) / task_dir.name
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(tests, dest)
    run_tests = task_dir / "run-tests.sh"
    if run_tests.is_file():
        shutil.copy2(run_tests, dest / "run-tests.sh")
    return dest


_CONTAINER_CHECKER_TEMPLATE = '''\
import os, subprocess, sys

CID = os.environ["EVAL_CONTAINER_ID"]
WORKDIR = os.environ.get("EVAL_CONTAINER_WORKDIR") or "/app"
TESTS = @TESTS_DIR@

def _run(*argv, timeout):
    return subprocess.run(list(argv), stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT, timeout=timeout)

# /tests is the official Terminal-Bench convention: tests reference each
# other and helper files via /tests/... (or $TEST_DIR), so staging anywhere
# else breaks those tasks. Copied at GRADE time only — the agent never sees
# the grading code. rm first: with a pre-existing /tests (image-baked or
# rerun) podman cp would nest INTO it and pytest would collect both trees.
_run("podman", "exec", CID, "rm", "-rf", "/tests", timeout=20)
proc = _run("podman", "cp", TESTS, CID + ":/tests", timeout=20)
if proc.returncode != 0:
    print("podman cp failed:", proc.stdout.decode("utf-8", "replace")[-500:])
    sys.exit(1)
# Grade via the task's own run-tests.sh when staged — the official entry
# point installs the test toolchain (gcc, pinned pytest, ...) and does
# pre-steps bare pytest misses (e.g. `mv $TEST_DIR/src`). It needs network;
# container cases default to network on. Fallback: plain pytest.
has_script = _run("podman", "exec", CID, "test", "-f",
                  "/tests/run-tests.sh", timeout=10).returncode == 0
if has_script:
    proc = _run("podman", "exec", "-e", "TEST_DIR=/tests",
                "--workdir", WORKDIR, CID,
                "bash", "/tests/run-tests.sh", timeout=420)
else:
    proc = _run("podman", "exec", "-e", "TEST_DIR=/tests",
                "--workdir", WORKDIR, CID,
                "python3", "-m", "pytest", "/tests", "-q", timeout=95)
if proc.returncode != 0:
    print(proc.stdout.decode("utf-8", "replace")[-3000:])
sys.exit(proc.returncode)
'''


def build_container_checker(tests_dir) -> str:
    """The full-mode expect.checker: copy the staged tests into the running
    case container (the agent never sees them — they live host-side under the
    data dir until grading) and run pytest there. Exit code propagates."""
    return _CONTAINER_CHECKER_TEMPLATE.replace("@TESTS_DIR@",
                                               repr(str(tests_dir)))


def _rewrite_instruction_full(instruction: str) -> str:
    """Full mode runs inside the task's own container: /app IS the agent's
    working directory, so container paths stay verbatim — unlike lite mode,
    which rewrites /app to the eval sandbox's work root. The fs.* hint
    prevents the classic lost-output failure: host file tools are confined to
    the sandbox (the bind-mounted /app), so an absolute '/app/x' path there
    misses; terminal paths inside code.run/code.execute really are /app/..."""
    return (instruction.strip()
            + "\n\nWork in /app — your current working directory. Host file "
              "tools (fs.*) see /app as the project root: use RELATIVE paths "
              "with them; absolute /app/... paths are for the terminal "
              "(code.run/code.execute) only.")


# Marathon tasks need a bounded but generous turn cap — 1200s covers slow
# local brains on build/RL tasks without one stuck case eating the suite's
# whole evening (the global eval.turn_wall_clock_s default stays 1800).
TB_FULL_TURN_WALL_CLOCK_S = 1200

_TB_COMPOSE_NAMES = ("docker-compose.yaml", "docker-compose.yml")


def tb_compose_dir(task_dir: Path) -> Path | None:
    """The task dir when it ships a MULTI-service compose stack (the runner
    starts the whole stack per case instead of a lone client container);
    None for single-service/absent/unparseable compose files, which keep the
    plain single-container case shape."""
    task_dir = Path(task_dir)
    for name in _TB_COMPOSE_NAMES:
        f = task_dir / name
        if not f.is_file():
            continue
        try:
            doc = yaml.safe_load(f.read_text(encoding="utf-8",
                                             errors="replace")) or {}
        except yaml.YAMLError:
            return None
        services = doc.get("services") if isinstance(doc, dict) else None
        if isinstance(services, dict) and len(services) > 1:
            return task_dir
        return None
    return None


def tb_task_to_case_full(task_dir: Path, image: str, tests_stage: Path) -> dict:
    """Convert one terminal-bench task into a CONTAINER eval case (full
    mode). No project fixtures: the image already contains the whole task
    environment — that's the point of full mode. Cases get outbound network
    (official Terminal-Bench allows downloads; the container is throwaway and
    credential-free) and a per-case turn cap. Multi-service tasks (a compose
    file with >1 service) additionally pin `container.compose` to the task
    dir: the runner then brings up the whole stack per case via
    podman-compose, with `image` handed to compose as
    T_BENCH_TASK_DOCKER_CLIENT_IMAGE_NAME (no rebuild at run time)."""
    task_dir = Path(task_dir)
    name = task_dir.name
    if not task_dir.is_dir():
        raise SkipTask(f"no such task directory: {name}")
    try:
        meta = yaml.safe_load((task_dir / "task.yaml").read_text(
            encoding="utf-8", errors="replace")) or {}
    except (OSError, yaml.YAMLError) as e:
        raise SkipTask(f"bad task.yaml: {e}") from e
    instruction = str(meta.get("instruction") or "").strip()
    if not instruction:
        raise SkipTask("task.yaml has no instruction")
    container = {"image": str(image), "workdir": "/app", "network": True}
    compose_dir = tb_compose_dir(task_dir)
    if compose_dir is not None:
        container["compose"] = str(compose_dir.resolve())
        container["client_service"] = "client"
    return {
        "id": sanitize_task_id("tb", name),
        "name": f"Terminal-Bench: {name}",
        "tags": ["bench", "tb", "tb-full"],
        "driver": "scripted",
        "turns": [{"user": _rewrite_instruction_full(instruction)}],
        "container": container,
        "budget": {"turn_wall_clock_s": TB_FULL_TURN_WALL_CLOCK_S},
        "expect": {"checker": build_container_checker(tests_stage)},
        "judge_rubric": TB_JUDGE_RUBRIC,
    }


# ---- GAIA -----------------------------------------------------------------------

GAIA_DATASET = "gaia-benchmark/GAIA"
_GAIA_ROWS_URL = ("https://datasets-server.huggingface.co/rows"
                  "?dataset=gaia-benchmark%2FGAIA&config=2023_level1"
                  "&split=validation&offset={offset}&length={length}")
_GAIA_FILE_URL = ("https://huggingface.co/datasets/gaia-benchmark/GAIA"
                  "/resolve/main/{path}")
_GAIA_MAX_ATTACHMENT = 256 * 1024

# The official GAIA prompt suffix (Mialon et al. 2023, arXiv:2311.12983,
# appendix) — the harness's answer_exact_any scorer keys on the FINAL ANSWER
# marker, exactly like the real GAIA scorer.
GAIA_SUFFIX = (
    "You are a general AI assistant. I will ask you a question. Report your "
    "thoughts, and finish your answer with the following template: "
    "FINAL ANSWER: [YOUR FINAL ANSWER]. YOUR FINAL ANSWER should be a number "
    "OR as few words as possible OR a comma separated list of numbers and/or "
    "strings. If you are asked for a number, don't use comma to write your "
    "number neither use units such as $ or percent sign unless specified "
    "otherwise. If you are asked for a string, don't use articles, neither "
    "abbreviations (e.g. for cities), and write the digits in plain text "
    "unless specified otherwise. If you are asked for a comma separated "
    "list, apply the above rules depending of whether the element to be put "
    "in the list is a number or a string.")

GAIA_JUDGE_RUBRIC = "Exact-match case: pass iff deterministic checks passed."

GAIA_TOKEN_HELP = ("GAIA is a gated HF dataset: set HF_TOKEN in the service "
                   "environment (e.g. ~/.config/jaynet.env) to a token with "
                   "read access to gaia-benchmark/GAIA, then restart. The "
                   "token is read from the process env and never logged.")


def _http_get(url: str, token: str | None, timeout: int = 60) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "jaynet-benchlab"})
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.read()
    except urllib.error.HTTPError as e:
        if e.code in (401, 403):
            raise RuntimeError("HF rejected the token (gated dataset). "
                               + GAIA_TOKEN_HELP) from e
        # The datasets-server answers "gated + no access" with a 404 whose
        # body SAYS so — surface HF's own explanation instead of a bare
        # "not found" that sends operators hunting for a wrong URL.
        try:
            detail = e.read().decode("utf-8", "replace").strip()[:300]
        except OSError:
            detail = ""
        msg = f"HTTP {e.code} from Hugging Face: {url}"
        if detail:
            msg += f" — {detail}"
        if e.code == 404:
            msg += " (a 404 here usually means the token has no access to " \
                   "the gated dataset — " + GAIA_TOKEN_HELP + ")"
        raise RuntimeError(msg) from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"cannot reach Hugging Face: {e.reason}") from e


def fetch_gaia_rows(token: str, limit: int = 50) -> list[dict]:
    """Level-1 validation rows via the HF datasets-server (no `datasets`
    package needed). `limit` caps how many rows are pulled."""
    rows: list[dict] = []
    offset = 0
    while len(rows) < limit:
        length = min(100, limit - len(rows))
        data = json.loads(_http_get(
            _GAIA_ROWS_URL.format(offset=offset, length=length), token))
        batch = data.get("rows") or []
        if not batch:
            break
        rows.extend(b.get("row") or {} for b in batch)
        offset += len(batch)
    return rows[:limit]


def fetch_gaia_attachment(token: str, file_path: str) -> bytes:
    """Download one GAIA attachment file from the dataset repo."""
    quoted = urllib.parse.quote(str(file_path).lstrip("/"))
    return _http_get(_GAIA_FILE_URL.format(path=quoted), token, timeout=120)


def gaia_row_to_case(row: dict, attachment: bytes | None = None,
                     attachment_name: str = "") -> dict:
    """Convert one GAIA metadata row (+ optional downloaded attachment bytes)
    into an answer_exact_any eval case dict."""
    question = str(row.get("Question") or "").strip()
    # HF's schema spells it "Final answer" (space); accept the underscore
    # variant too so older fixtures/fixtures by hand keep working.
    gold = str(row.get("Final answer") or row.get("Final_answer")
               or "").strip()
    task_id = str(row.get("task_id") or "").strip()
    if not question or not gold or not task_id:
        raise SkipTask("row misses Question/Final_answer/task_id")
    turn = question
    project: dict = {}
    if attachment_name:
        if attachment is None:
            raise SkipTask(f"attachment '{attachment_name}' not downloaded")
        if len(attachment) > _GAIA_MAX_ATTACHMENT:
            raise SkipTask(f"attachment '{attachment_name}' too large "
                           f"({len(attachment)} bytes)")
        project = _fixtures_to_project({attachment_name: attachment})
        turn += (f"\n\nThe referenced file '{attachment_name}' is in the "
                 f"current project directory.")
    turn += "\n\n" + GAIA_SUFFIX
    short = question if len(question) <= 70 else question[:67].rstrip() + "..."
    case = {
        "id": sanitize_task_id("gaia", task_id[:8]),
        "name": f"GAIA level-1: {short}",
        "tags": ["bench", "gaia"],
        "driver": "scripted",
        "turns": [{"user": turn}],
        "expect": {"answer_exact_any": [gold]},
        "judge_rubric": GAIA_JUDGE_RUBRIC,
    }
    if project:
        case["project"] = project
    return case


# ---- writing ---------------------------------------------------------------------

def write_cases(cases: list[dict], out_dir: Path) -> dict:
    """Validate, dump and write each case as <id>.yaml into out_dir (the
    custom evals layer — cases show up in Admin → Eval). Each written file is
    parsed back as proof. Only ids we generated (tb-*/gaia-*) are written, so
    re-imports overwrite benchlab's own cases and never touch other files."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    imported: list[str] = []
    failed: list[dict] = []
    for case in cases:
        cid = str(case.get("id") or "?")
        try:
            errors = validate_case_dict(cid, case)
            if errors:
                raise ValueError("; ".join(errors))
            text = yaml.safe_dump(case, sort_keys=False, allow_unicode=True,
                                  width=100)
            parse_case(cid, text, "custom")          # prove the file loads
            (out_dir / f"{cid}.yaml").write_text(text, encoding="utf-8")
            imported.append(cid)
        except (ValueError, OSError, yaml.YAMLError) as e:
            log.warning("benchlab: case %s failed to write: %s", cid, e)
            failed.append({"id": cid, "error": str(e)})
    return {"imported": imported, "failed": failed, "dir": str(out_dir)}
