"""Regenerate docs/catalog.md — the tools/skills/chains/slash catalogue.

Descriptions show the first line only (same convention as the composer's
slash preview); the model sees the full text at run time. Slash commands are
parsed from web/static/app.js (SLASH_META), tools from the registry, skills
and chains from their files.

Usage (live venv, from the dev checkout):
  /srv/orchestrator/.venv/bin/python scripts/gen_catalog.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


def first_line(text: str, cap: int = 130) -> str:
    line = re.sub(r"\s+", " ", (text or "").split("\n")[0].strip())
    if len(line) > cap:
        line = line[:cap].rstrip() + "…"
    return line or "—"


def slash_rows() -> list[tuple[str, str]]:
    js = (ROOT / "web/static/app.js").read_text()
    block = js.split("const SLASH_META=[", 1)[1].split("];", 1)[0]
    return re.findall(r'name:"([^"]+)",\s*desc:"([^"]+)"', block)


def tool_sections() -> tuple[int, str]:
    from runtime.registry import ToolRegistry
    reg = ToolRegistry(ROOT / "tools")
    reg.discover()
    by_ns: dict[str, list] = {}
    for name, t in sorted(reg._tools.items()):
        by_ns.setdefault(name.split(".")[0], []).append(t)
    parts = []
    for ns in sorted(by_ns):
        parts.append(f"### {ns}\n\n| Tool | Description | Flags |\n|---|---|---|")
        for t in sorted(by_ns[ns], key=lambda x: x.name):
            flags = ", ".join(f for f, on in
                              (("private", t.private),
                               ("confirm", t.requires_confirmation)) if on)
            parts.append(f"| `{t.name}` | {first_line(t.description)} | {flags} |")
        parts.append("")
    return len(reg._tools), "\n".join(parts)


def skill_rows() -> list[tuple[str, str]]:
    rows = []
    for d in sorted((ROOT / "skills").iterdir()):
        f = d / "SKILL.md"
        if not f.is_file():
            continue
        meta: dict[str, str] = {}
        in_fm = False
        for line in f.read_text().splitlines():
            if line.strip() == "---":
                if in_fm:
                    break
                in_fm = True
                continue
            if in_fm and ":" in line:
                k, v = line.split(":", 1)
                meta[k.strip()] = v.strip()
        rows.append((meta.get("name", d.name), meta.get("description", "")))
    return rows


def chain_rows() -> list[tuple[str, str]]:
    import yaml
    rows = []
    for f in sorted((ROOT / "chains").glob("*.yaml")):
        d = yaml.safe_load(f.read_text()) or {}
        rows.append((f.stem, d.get("description", "")))
    return rows


def main():
    n_tools, tools_md = tool_sections()
    slash = slash_rows()
    skills = skill_rows()
    chains = chain_rows()

    out = [
        "# Catalogue — tools, skills, chains, slash commands",
        "",
        "> Generated by `scripts/gen_catalog.py` — re-run it after adding or",
        "> editing tools, skills or chains. Descriptions show the first line;",
        "> the model sees the full text, and Admin → Tools toggles what is offered.",
        "",
        "## Slash commands",
        "",
        "Type `/` in the composer to pop the filtered list; `<namespace>.` drills",
        "into that namespace's tools, Tab completes.",
        "",
        "| Command | What it does |",
        "|---|---|",
    ]
    out += [f"| `/{n}` | {d} |" for n, d in slash]
    out += ["", f"## Tools ({n_tools})", "",
            "`private` = results taint the conversation for cloud calls; "
            "`confirm` = asks before running.", ""]
    out.append(tools_md)
    out += ["## Skills", "",
            "Know-how documents the brain loads on demand "
            "(built-ins below; the Studio adds customs).", "",
            "| Skill | Description |", "|---|---|"]
    out += [f"| `{n}` | {first_line(d, 200)} |" for n, d in skills]
    out += ["", "## Chains", "",
            "Named YAML pipelines, run via `chain.run(name=…, input=…)`.", "",
            "| Chain | Description |", "|---|---|"]
    out += [f"| `{n}` | {first_line(d, 200)} |" for n, d in chains]
    out.append("")

    (ROOT / "docs/catalog.md").write_text("\n".join(out))
    print(f"docs/catalog.md: {n_tools} tools, {len(skills)} skills, "
          f"{len(chains)} chains, {len(slash)} slash commands")


if __name__ == "__main__":
    main()
